Add simple stats API
proxy-wasm/proxy-wasm-rust-sdk pull request #242
Opened 2024-07-11 18:32 UTC by junr03

This PR exposes the concept of Metrics with a high level API. It takes liberal inspiration from the Simple<Counter,Gauge,Histogram> in the CPP SDK.

Users of the Rust SDK will now be able to create and manipulate simple Counters, Gauges, and Histograms that exist in the Envoy Runtime.

Note that this change is more generic than https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/229 given that it exposes the concept of Counters, Gauges, and Histograms as a first class implementation, rather than interacting directly with the metrics host calls via the Root Context.

cc @casimiro

2024-07-11 20:17 UTC, adilhafeez reviewed
It would be great if you can update one of the examples and show use of stats there.

2024-07-11 20:17 UTC, adilhafeez commented on src/stats.rs
> +        // A Counter can only be incremented.
Should we throw an exception here or maybe have separate trait called `MetricCounter` and place `increment` there.

2024-07-15 16:52 UTC, adilhafeez approved these changes

2024-11-28 09:45 UTC, Swaagie requested changes
I've actually tested this local on a project and it works nicely. @PiotrSikora what is your opinion on this vs the other metric PR?

2024-11-28 09:45 UTC, Swaagie commented on examples/metrics/README.md
> +## Proxy-Wasm plugin example: HTTP headers
```suggestion
## Proxy-Wasm plugin example: Metrics
```

2024-11-28 09:45 UTC, Swaagie commented on examples/metrics/README.md
> +Proxy-Wasm plugin that logs HTTP request/response headers.
Please update this as well.

2024-11-28 09:45 UTC, Swaagie commented on examples/metrics/README.md
> +$ cargo build --target wasm32-wasi --release
```suggestion
$ cargo build --target wasm32-wasip1 --release
```

2025-06-21 23:05 UTC, closed without merging